language: python                
matrix:
  include:
    - os: linux
      sudo: required
      python: pypy
    - os: linux
      sudo: required
      python: 2.7
    - os: linux
      sudo: required
      python: 3.5
    - os: linux
      sudo: required
      python: 3.6
    - os: linux
      sudo: required
      dist: xenial
      python: 3.7
install:
  - pip install .
script: make test