application: prestans-demo
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on

libraries:
- name: PIL
  version: latest
- name: webob
  version: latest
- name: jinja2
  version: latest
- name: webapp2
  version: latest

handlers:

# Static directory maps for the application
- url: /css
  static_dir: ../statis/css
  #static_dir: static/web/assets
  login: admin

- url: /js
  static_dir: ../client/
  #static_dir: static/web/js
  login: admin

- url: /api/.*
  script: entry.api

- url: /.*
  script: entry.frontend
