name: prestans-demo
version: 1.0
bind: localhost
port: 8000

append_path:
- app/

environ:
- key: app_config
  value: config/pdemo.cfg

static:
- url: /img
  path: static/img

default_app: entry.frontend

sub_modules:

- url: /api
  module: entry.api
