name: prestans-demo
version: 1.0
bind: localhost
port: 8000

append_path:
- ext/
- app/

environ:
- key: app_config
  value: config/app.config

static:
- url: /img
  path: static/img

handlers:
- url: /api
  module: pdemo.handler.application
